#!/usr/bin/env python3

import sys, os

if sys.version_info < (3,7,0):
    print('** FATAL ERROR: Greaseweazle requires Python 3.7 or later')
    sys.exit(1)

# Update the search path and import the real script
sys.path[0] = os.path.join(sys.path[0], "scripts")
import gw

# Execute the real script
gw.main(sys.argv)
